import {useFrame} from '@react-three/fiber';
import {Text} from '@react-three/drei';
import {useRef} from 'react';
import * as THREE from 'three';
import {useGame,Vec} from '../store';

const districts=[['DOWNTOWN',0,-18,0],['RESIDENTIAL',-38,12,0],['INDUSTRIAL',38,14,0],['BEACH',0,48,0],['AIRPORT',58,-40,0],['HARBOR',-52,-34,0],['RURAL',-65,50,0]] as const;
const spots=[['POLICE',-16,-4],['HOSPITAL',18,-4],['BANK',8,-20],['DEALERSHIP',-8,-20],['GARAGE',-25,-15],['GAS',24,-18],['PARK',0,8],['SHOPS',16,14]] as const;
function Building({x,z,w=5,h=5,d=5}:{x:number;z:number;w?:number;h?:number;d?:number}){return <mesh position={[x,h/2,z]} castShadow><boxGeometry args={[w,h,d]}/><meshStandardMaterial color={h>8?'#202b42':'#18243a'} roughness={.75}/></mesh>}
function Road({x=0,z=0,w=8,d=100}:{x?:number;z?:number;w?:number;d?:number}){return <mesh rotation={[-Math.PI/2,0,0]} position={[x,.01,z]}><planeGeometry args={[w,d]}/><meshStandardMaterial color="#171b25"/></mesh>}
function City(){const buildings=[];for(let x=-45;x<=45;x+=9)for(let z=-45;z<=45;z+=9){if(Math.abs(x)<7||Math.abs(z)<7)continue;const h=4+((Math.abs(x*13+z*7)%9));buildings.push(<Building key={`${x}:${z}`} x={x} z={z} w={5.5} d={5.5} h={h}/>)}return <group>{buildings}<Road w={12}/><Road w={12} d={110} x={0}/><Road w={12} d={110} x={-36}/><Road w={12} d={110} x={36}/><Road w={110} d={12} z={0}/><Road w={110} d={12} z={-27}/><Road w={110} d={12} z={27}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.01,55]}><planeGeometry args={[120,35]}/><meshStandardMaterial color="#16415a"/></mesh>{districts.map(([n,x,z])=><Text key={n} position={[x,9,z]} fontSize={2.2} color="#67e8f9" anchorX="center" outlineWidth={.04} outlineColor="#061018">{n}</Text>)}{spots.map(([n,x,z])=><Text key={n} position={[x,2.8,z]} fontSize={.8} color="#f4f7ff" anchorX="center">{n}</Text>)}</group>}
function Vehicle({position,color,remote=false}:{position:Vec;color:string;remote?:boolean}){return <group position={[position.x,.75,position.z]} rotation={[0,position.y,0]}><mesh castShadow><boxGeometry args={[2.1,.8,4]}/><meshStandardMaterial color={color}/></mesh><mesh position={[0,.55,-.1]}><boxGeometry args={[1.65,.65,1.65]}/><meshStandardMaterial color="#101827" metalness={.2}/></mesh>{[-.8,.8].flatMap(x=>[-1.2,1.2].map(z=><mesh key={`${x}${z}`} position={[x,-.4,z]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.38,.38,.25,16]}/><meshStandardMaterial color="#090b10"/></mesh>))}{remote&&<Text position={[0,2.1,0]} fontSize={.35} color="#8be9fd" anchorX="center">PLAYER VEHICLE</Text>}</group>}
function LocalPlayer(){const ref=useRef<THREE.Group>(null);const keys=useRef<Record<string,boolean>>({});const setPosition=useGame(s=>s.setPosition);const pos=useGame(s=>s.position);const vehicle=useGame(s=>s.vehicle);useFrame((_,dt)=>{if(!ref.current)return;const k=keys.current;const speed=(k.ShiftLeft||k.ShiftRight?10:5)*(vehicle?1.8:1);let dx=0,dz=0;if(k.KeyW)dz-=1;if(k.KeyS)dz+=1;if(k.KeyA)dx-=1;if(k.KeyD)dx+=1;const len=Math.hypot(dx,dz)||1;const nx=THREE.MathUtils.clamp(ref.current.position.x+dx/len*speed*dt,-72,72);const nz=THREE.MathUtils.clamp(ref.current.position.z+dz/len*speed*dt,-65,65);ref.current.position.x=nx;ref.current.position.z=nz;if(dx||dz)ref.current.rotation.y=Math.atan2(dx,dz);setPosition({x:nx,y:ref.current.rotation.y,z:nz});});
const down=(e:KeyboardEvent)=>{keys.current[e.code]=true;if(e.code==='KeyF')useGame.getState().setVehicle(useGame.getState().vehicle?'': 'sedan')};const up=(e:KeyboardEvent)=>{keys.current[e.code]=false};
if(typeof window!=='undefined'){window.onkeydown=down;window.onkeyup=up;}return <group ref={ref} position={[pos.x,.9,pos.z]}><mesh castShadow position={[0,.9,0]}><capsuleGeometry args={[.42,.9,6,12]}/><meshStandardMaterial color="#4f8cff"/></mesh><mesh castShadow position={[0,1.65,0]}><sphereGeometry args={[.36,16,12]}/><meshStandardMaterial color="#d6a27a"/></mesh><Text position={[0,2.35,0]} fontSize={.48} color="#fff" anchorX="center">{useGame.getState().name}</Text>{vehicle&&<Vehicle position={{x:0,y:0,z:0}} color="#f23b72"/>}</group>}
export function World(){return <><ambientLight intensity={.65}/><directionalLight castShadow intensity={1.5} position={[30,45,20]} shadow-mapSize-width={1024} shadow-mapSize-height={1024}/><fog attach="fog" args={['#07101b',45,125]}/><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[150,150]}/><meshStandardMaterial color="#263b2e"/></mesh><City/><LocalPlayer/><OtherPlayers/></>}
function OtherPlayers(){const remotes=useGame(s=>s.remotes);return <>{Object.values(remotes).map(p=><group key={p.id} position={[p.position.x,.9,p.position.z]}><mesh castShadow><capsuleGeometry args={[.4,.85,6,12]}/><meshStandardMaterial color="#ff8a4c"/></mesh><mesh position={[0,1.55,0]}><sphereGeometry args={[.34,16,12]}/><meshStandardMaterial color="#d6a27a"/></mesh><Text position={[0,2.25,0]} fontSize={.42} color="#fef08a" anchorX="center">{p.name}</Text>{p.vehicle&&<Vehicle position={{x:0,y:0,z:0}} color="#8b5cf6" remote/>}</group>)}</>}
