create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, username text not null check(length(username) between 2 and 18), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.player_stats(player_id uuid primary key references public.profiles(id) on delete cascade,cash bigint not null default 250,bank bigint not null default 500,level int not null default 1,xp int not null default 0,health int not null default 100,stamina int not null default 100,reputation int not null default 0,updated_at timestamptz not null default now());
create table if not exists public.player_inventory(player_id uuid primary key references public.profiles(id) on delete cascade,items jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
create table if not exists public.vehicles(id uuid primary key default gen_random_uuid(),name text not null,kind text not null,price bigint not null,top_speed numeric not null default 10,created_at timestamptz not null default now());
create table if not exists public.player_vehicles(id uuid primary key default gen_random_uuid(),player_id uuid not null references public.profiles(id) on delete cascade,vehicle_id uuid not null references public.vehicles(id),health int not null default 100,fuel int not null default 100,created_at timestamptz not null default now());
create table if not exists public.properties(id uuid primary key default gen_random_uuid(),name text not null,kind text not null,price bigint not null,location jsonb not null default '{}'::jsonb);
create table if not exists public.player_properties(id uuid primary key default gen_random_uuid(),player_id uuid not null references public.profiles(id) on delete cascade,property_id uuid not null references public.properties(id),purchased_at timestamptz not null default now(),unique(player_id,property_id));
create table if not exists public.jobs(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text not null,reward bigint not null,xp_reward int not null,active boolean not null default true);
create table if not exists public.job_progress(id uuid primary key default gen_random_uuid(),player_id uuid not null references public.profiles(id) on delete cascade,job_id uuid not null references public.jobs(id),status text not null default 'active',objective jsonb not null default '{}'::jsonb,started_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists public.transactions(id uuid primary key default gen_random_uuid(),player_id uuid not null references public.profiles(id) on delete cascade,type text not null,amount bigint not null,description text not null,created_at timestamptz not null default now());
create table if not exists public.chat_messages(id uuid primary key default gen_random_uuid(),player_id uuid references public.profiles(id) on delete set null,username text not null,message text not null check(length(message) between 1 and 160),channel text not null default 'global',created_at timestamptz not null default now());
create table if not exists public.player_presence(player_id uuid primary key references public.profiles(id) on delete cascade,position jsonb not null default '{"x":0,"y":0,"z":0}',rotation numeric not null default 0,vehicle text,updated_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.player_stats enable row level security; alter table public.player_inventory enable row level security; alter table public.player_vehicles enable row level security; alter table public.player_properties enable row level security; alter table public.job_progress enable row level security; alter table public.transactions enable row level security; alter table public.chat_messages enable row level security; alter table public.player_presence enable row level security;
create policy "profiles readable" on public.profiles for select to authenticated using (true); create policy "own profile" on public.profiles for insert to authenticated with check(auth.uid()=id); create policy "own profile update" on public.profiles for update to authenticated using(auth.uid()=id);
create policy "own stats read" on public.player_stats for select to authenticated using(auth.uid()=player_id); create policy "own inventory read" on public.player_inventory for select to authenticated using(auth.uid()=player_id); create policy "own vehicles read" on public.player_vehicles for select to authenticated using(auth.uid()=player_id); create policy "own properties read" on public.player_properties for select to authenticated using(auth.uid()=player_id); create policy "jobs public read" on public.jobs for select to authenticated using(active=true); create policy "own progress" on public.job_progress for select to authenticated using(auth.uid()=player_id); create policy "transactions own read" on public.transactions for select to authenticated using(auth.uid()=player_id); create policy "chat read" on public.chat_messages for select to authenticated using(true); create policy "chat insert" on public.chat_messages for insert to authenticated with check(auth.uid()=player_id); create policy "presence read" on public.player_presence for select to authenticated using(true); create policy "presence own write" on public.player_presence for insert to authenticated with check(auth.uid()=player_id); create policy "presence own update" on public.player_presence for update to authenticated using(auth.uid()=player_id);

create or replace function public.new_player() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,username) values(new.id,'Rider-'||substr(new.id::text,1,5)) on conflict do nothing; insert into public.player_stats(player_id) values(new.id) on conflict do nothing; insert into public.player_inventory(player_id) values(new.id) on conflict do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.new_player();

insert into public.vehicles(name,kind,price,top_speed) values ('Metro Sedan','sedan',1200,10),('Volt Sports','sports',6500,15),('Hauler Pickup','pickup',3000,9),('City Taxi','taxi',1800,10) on conflict do nothing;
insert into public.jobs(slug,name,description,reward,xp_reward) values ('delivery','Delivery','Pick up a package downtown and deliver it to the marked depot.',180,60),('taxi','Taxi Driver','Pick up a passenger and deliver them safely.',220,75),('truck','Truck Driver','Move cargo from the industrial district to the harbor.',400,120),('mechanic','Mechanic','Repair a nearby vehicle.',150,50) on conflict(slug) do nothing;
insert into public.properties(name,kind,price,location) values ('Sunset Apartment','apartment',15000,'{"x":-34,"z":16}'),('Downtown Garage','garage',22000,'{"x":-25,"z":-15}') on conflict do nothing;

create or replace function public.complete_job(p_job_slug text) returns jsonb language plpgsql security definer set search_path=public as $$ declare j jobs; r jsonb; begin select * into j from jobs where slug=p_job_slug and active=true limit 1; if j.id is null then raise exception 'job_not_found'; end if; update player_stats set cash=cash+j.reward,xp=xp+j.xp_reward,level=1+floor((xp+j.xp_reward)/500),updated_at=now() where player_id=auth.uid(); insert into transactions(player_id,type,amount,description) values(auth.uid(),'job_reward',j.reward,j.name); r:=jsonb_build_object('cash',j.reward,'xp',j.xp_reward,'job',j.slug); return r; end $$;
revoke all on function public.complete_job(text) from public; grant execute on function public.complete_job(text) to authenticated;
