import {Canvas,useFrame} from '@react-three/fiber';
import {PerspectiveCamera} from '@react-three/drei';
import {useEffect,useRef,useState} from 'react';
import {supabase,ready} from './lib/supabase';
import {useGame,Remote} from './store';
import {World} from './game/World';

function CameraFollow(){const camera=useRef<any>(null);const p=useGame(s=>s.position);useFrame(()=>{if(!camera.current)return;const target={x:p.x,y:2.2,z:p.z};camera.current.position.lerp({x:target.x,y:target.y+6,z:target.z+9} as any,.08);camera.current.lookAt(target.x,target.y,target.z)});return <PerspectiveCamera ref={camera} makeDefault position={[0,7,17]} fov={62}/>}
function Landing({onPlay}:{onPlay:()=>void}){return <main className="landing"><div className="heroGlow"/><nav><strong>NEON<span>CITY</span></strong><span className="online">● LIVE WORLD</span></nav><section><p className="eyebrow">A PERSISTENT ONLINE CITY</p><h1>YOUR CITY.<br/><em>YOUR STORY.</em></h1><p className="lead">Explore a living 3D city, meet real players, drive, work jobs and build your reputation — directly in your browser.</p><button className="primary" onClick={onPlay}>PLAY NOW <span>→</span></button><div className="features"><b>3D OPEN WORLD</b><b>REAL MULTIPLAYER</b><b>DESKTOP + MOBILE</b></div></section></main>}
function CharacterSetup({onDone}:{onDone:(name:string)=>void}){const [name,setName]=useState('');return <div className="modal"><div className="panel setup"><p className="eyebrow">WELCOME TO NEON CITY</p><h2>Create your rider</h2><p>Choose a name other players will see above your character.</p><input autoFocus maxLength={18} placeholder="Player name" value={name} onChange={e=>setName(e.target.value.replace(/[^a-zA-Z0-9 _-]/g,''))}/><button className="primary" disabled={!name.trim()} onClick={()=>onDone(name.trim())}>ENTER CITY →</button></div></div>}
function HUD({onChat,onMap}:{onChat:()=>void;onMap:()=>void}){const s=useGame(x=>x.stats);const name=useGame(x=>x.name);const objective=useGame(x=>x.objective);return <div className="hud"><div className="top"><div className="brand">NEON<span>CITY</span></div><div className="player"><b>{name}</b><small>LVL {s.level} · {s.reputation} REP</small></div><div className="wallet">$ {s.cash.toLocaleString()} <small>BANK $ {s.bank.toLocaleString()}</small></div></div><div className="objective"><small>CURRENT OBJECTIVE</small><b>{objective}</b></div><div className="status"><div><span>HP</span><i><u style={{width:`${s.health}%`}}/></i></div><div><span>STAMINA</span><i><u style={{width:`${s.stamina}%`}}/></i></div></div><div className="minimap"><div className="mapGrid"/><span className="you">▲</span><small>NEON CITY</small></div><div className="actions"><button onClick={onMap}>M<br/><small>MAP</small></button><button onClick={onChat}>T<br/><small>CHAT</small></button><button onClick={()=>useGame.getState().setVehicle(useGame.getState().vehicle?'': 'sedan')}>F<br/><small>{useGame.getState().vehicle?'EXIT':'CAR'}</small></button></div><MobileControls/></div>}
function MobileControls(){const press=(code:string,on:boolean)=>{const e=new KeyboardEvent(on?'keydown':'keyup',{code});window.dispatchEvent(e)};return <div className="mobileControls"><div className="joystick" onTouchStart={()=>press('KeyW',true)} onTouchEnd={()=>press('KeyW',false)}><span/></div><div className="mobileBtns"><button onTouchStart={()=>press('ShiftLeft',true)} onTouchEnd={()=>press('ShiftLeft',false)}>RUN</button><button onClick={()=>press('Space',true)}>JUMP</button><button onClick={()=>press('KeyF',true)}>CAR</button></div></div>}
function Chat({close}:{close:()=>void}){const [messages,setMessages]=useState<{name:string;message:string}[]>([]);const [text,setText]=useState('');const name=useGame(s=>s.name);useEffect(()=>{if(!supabase)return;const c=supabase.channel('chat-global').on('broadcast',{event:'message'},({payload})=>setMessages(m=>[...m,payload as any].slice(-40))).subscribe();return()=>{supabase.removeChannel(c)}},[]);const send=async()=>{const value=text.trim().slice(0,160);if(!value||!supabase)return;await supabase.channel('chat-global').send({type:'broadcast',event:'message',payload:{name,message:value}});setMessages(m=>[...m,{name,message:value}].slice(-40));setText('')};return <div className="modal"><div className="panel chat"><header><b>GLOBAL CHAT</b><button onClick={close}>×</button></header><div className="messages">{messages.map((m,i)=><p key={i}><b>{m.name}</b> {m.message}</p>)}</div><div className="chatInput"><input value={text} maxLength={160} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Say something..."/><button onClick={send}>SEND</button></div></div></div>}
function Map({close}:{close:()=>void}){return <div className="modal"><div className="panel fullMap"><header><b>NEON CITY MAP</b><button onClick={close}>×</button></header><div className="cityMap">{['DOWNTOWN','RESIDENTIAL','INDUSTRIAL','BEACH','POLICE','HOSPITAL','BANK','DEALERSHIP','GARAGE','AIRPORT','HARBOR','PARK'].map((x,i)=><div key={x} className={`marker m${i}`}>{x}</div>)}</div></div></div>}
function Game(){const [chat,setChat]=useState(false),[map,setMap]=useState(false);const [connected,setConnected]=useState(false);const name=useGame(s=>s.name);const position=useGame(s=>s.position);const vehicle=useGame(s=>s.vehicle);const setRemotes=useGame(s=>s.setRemotes);useEffect(()=>{if(!supabase)return;let channel=supabase.channel('world-presence',{config:{presence:{key:crypto.randomUUID()}}});channel.on('presence',{event:'sync'},()=>{const state=channel.presenceState<Record<string,Remote>>();const next:Record<string,Remote>={};Object.entries(state).forEach(([id,rows])=>{const p=rows[0] as any;if(p.name!==name)next[id]={id,name:p.name,position:p.position,rotation:p.rotation||0,vehicle:p.vehicle}});setRemotes(next)}).subscribe(async status=>{setConnected(status==='SUBSCRIBED');if(status==='SUBSCRIBED')await channel.track({name,position,vehicle})});const timer=setInterval(()=>channel.track({name,position,vehicle}),120);return()=>{clearInterval(timer);supabase.removeChannel(channel)}},[name]);useEffect(()=>{useGame.getState().setObjective('Walk to the delivery hub near DOWNTOWN');},[]);return <div className="game"><Canvas shadows dpr={[1,1.5]} gl={{antialias:true}}><CameraFollow/><World/></Canvas><HUD onChat={()=>setChat(true)} onMap={()=>setMap(true)}/><div className={`connection ${connected?'ok':''}`}>{connected?'● ONLINE':'◌ CONNECTING'}</div>{chat&&<Chat close={()=>setChat(false)}/>} {map&&<Map close={()=>setMap(false)}/>}<div className="controlsHint">WASD move · SHIFT sprint · SPACE jump · F enter/exit · M map · T chat</div></div>}
export default function App(){const [started,setStarted]=useState(false);const [name,setName]=useState<string|null>(null);const [error,setError]=useState('');const setPlayerName=useGame(s=>s.setName);useEffect(()=>{if(!started||!supabase)return;supabase.auth.getSession().then(async({data})=>{if(!data.session){const {error}=await supabase.auth.signInAnonymously();if(error)setError('Supabase anonymous authentication is not enabled. Enable it in Authentication → Providers → Anonymous.')}})},[started]);if(!started)return <Landing onPlay={()=>setStarted(true)}/>;if(!ready)return <div className="fatal"><h2>NEON CITY</h2><p>Connect Supabase to start the online world.</p><code>VITE_SUPABASE_URL<br/>VITE_SUPABASE_ANON_KEY</code></div>;if(error)return <div className="fatal"><h2>Connection setup required</h2><p>{error}</p></div>;if(!name)return <CharacterSetup onDone={n=>{setName(n);setPlayerName(n)}}/>;return <Game/>}
